"""Deterministic fake LLM responses for full-stack self-tests.

Enabled via the FAKE_LLM env var (Settings.fake_llm). The gateway in
app/services/llm.py routes here instead of calling LiteLLM, so the entire
chat pipeline — SSE protocol, tool-call round-trip, persistence, metrics,
and the chatkit frontend — can be exercised end-to-end in E2E tests with
zero API cost and stable output.

The fake chat model behaves like a one-round tool user:
- First round (no tool results in the history): emits a search_highlights
  tool call, streamed in two argument fragments to exercise chunk buffering.
- Second round (history contains a tool result): streams a fixed text answer.
"""

import json
from types import SimpleNamespace
from typing import Any

FAKE_TOOL_CALL_ID = "fake_tool_call_1"
FAKE_ANSWER = "This is a deterministic fake answer based on your highlights."

# A valid coaching-card payload so coaching flows work under FAKE_LLM too.
FAKE_COACHING_CARD = {
    "title": "A Fake Card for Self-Tests",
    "body": "This card was generated by the fake LLM. It exists so end-to-end "
    "tests can exercise the coaching flow deterministically.",
    "chat_prompt": "Let's discuss the fake card.",
    "coaching_system_prompt": "You are a fake coach. Answer deterministically.",
}


def _chunk(
    *,
    content: str | None = None,
    tool_calls: list | None = None,
    finish_reason: str | None = None,
    usage: SimpleNamespace | None = None,
) -> SimpleNamespace:
    delta = SimpleNamespace(content=content, tool_calls=tool_calls)
    choice = SimpleNamespace(delta=delta, finish_reason=finish_reason)
    return SimpleNamespace(choices=[choice], usage=usage)


def _tool_call_delta(
    index: int, tool_id: str | None, name: str | None, args: str
) -> SimpleNamespace:
    return SimpleNamespace(
        index=index,
        id=tool_id,
        function=SimpleNamespace(name=name, arguments=args),
    )


def _final_usage() -> SimpleNamespace:
    return SimpleNamespace(prompt_tokens=100, completion_tokens=20)


async def fake_stream_chunks(messages: list[dict[str, Any]]):
    """Async generator of OpenAI-format chunks for one streaming round."""
    has_tool_result = any(m.get("role") == "tool" for m in messages)

    if not has_tool_result:
        # Round 1: request a search_highlights tool call, arguments split
        # across chunks to exercise the buffering path.
        yield _chunk(
            tool_calls=[_tool_call_delta(0, FAKE_TOOL_CALL_ID, "search_highlights", '{"query"')]
        )
        yield _chunk(tool_calls=[_tool_call_delta(0, None, None, ': "fake"}')])
        yield _chunk(finish_reason="tool_calls", usage=_final_usage())
        return

    # Round 2: stream the final text answer in a few pieces.
    words = FAKE_ANSWER.split(" ")
    mid = len(words) // 2
    yield _chunk(content=" ".join(words[:mid]) + " ")
    yield _chunk(content=" ".join(words[mid:]))
    yield _chunk(finish_reason="stop", usage=_final_usage())


def fake_completion_text(messages: list[dict[str, Any]]) -> str:
    """Deterministic non-streaming response (coaching expects JSON)."""
    return json.dumps(FAKE_COACHING_CARD)


# ---------------------------------------------------------------------------
# Fake highlight extractor (vision pipeline) for full-stack self-tests.
#
# The add-highlight E2E flow needs deterministic extraction results without
# vision API calls. Behavior is keyed off the user's instructions text:
#   - contains "FAKE_EMPTY"   -> empty extraction (the service's failure shape)
#   - contains "FAKE_NOMATCH" -> not_found match (highlight isn't in full_text;
#                                (0, 0) sentinel span, never a whole-page one)
#   - otherwise               -> a clean exact-substring extraction whose span
#                                crosses a hyphenated line break, so saving
#                                exercises the offset-slice + rejoin rule.
# ---------------------------------------------------------------------------

FAKE_PAGE_TEXT = (
    "The quick brown fox jumps over the lazy dog. It was a beau-\n"
    "tiful morning in the quiet town, and the streets were still\n"
    "empty. Birds sang softly from the rooftops."
)
FAKE_HIGHLIGHT_RAW = "It was a beau-\ntiful morning in the quiet town,"
# What the editor should save after hyphen rejoin + line-break collapse:
FAKE_HIGHLIGHT_SAVED = "It was a beautiful morning in the quiet town,"


class FakeHighlightExtractorService:
    """Drop-in fake for HighlightExtractorService under FAKE_LLM."""

    async def extract_highlight(
        self,
        image_bytes: bytes,
        filename: str,
        instructions: str,
        db: Any = None,
        highlight_id: int | None = None,
    ):
        from app.services.highlight_extractor import ExtractedHighlight

        if "FAKE_EMPTY" in instructions:
            return ExtractedHighlight(
                full_text="", highlight_text="", confidence="low", page_number=None
            )

        if "FAKE_NOMATCH" in instructions:
            # Matcher couldn't locate the passage: not_found with the (0, 0)
            # sentinel span (never a fabricated whole-page selection).
            return ExtractedHighlight(
                full_text=FAKE_PAGE_TEXT,
                highlight_text="This passage does not appear on the page.",
                confidence="high",  # honest UI must not trust this
                page_number="42",
                highlight_start=0,
                highlight_end=0,
                match_status="not_found",
                match_quality=0.0,
            )

        start = FAKE_PAGE_TEXT.find(FAKE_HIGHLIGHT_RAW)
        return ExtractedHighlight(
            full_text=FAKE_PAGE_TEXT,
            highlight_text=FAKE_HIGHLIGHT_RAW,
            confidence="high",
            page_number="42",
            highlight_start=start,
            highlight_end=start + len(FAKE_HIGHLIGHT_RAW),
            match_status="exact",
            match_quality=1.0,
        )
